name = "menu-llm-worker"
main = "src/index.js"
compatibility_date = "2025-05-17"

account_id = "330239b1c608a24cedc67ec8374395f2"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_id = "MENUS_DB"

[[kv_namespaces]]
binding = "SESSIONS"
id = "<TU_KV_NAMESPACE_ID>"
