# Nombre del servicio Cloudflare Workers.
name = "menu-llm-worker"

# Punto de entrada del worker para arrancar la función fetch().
main = "src/index.js"

compatibility_date = "2025-05-17"

# Account ID en Cloudflare
account_id = "330239b1c608a24cedc67ec8374395f2"

workers_dev = true

# ——————— D1 (SQLite en el Edge) ———————
[[d1_databases]]
binding = "DB"
database_name = "MENUS_DB"
database_id = "6056c696-b539-4389-a8a5-4c8607444def"

# ——————— KV (clave-valor distribuido) ———————
[[kv_namespaces]]
binding = "SESSIONS"
id = "813e9cd3a97f4d18883de727854666f6"

#——————— Pages (build) ———————
[[build]]
command = "npm install --prefix frontend && npm run build --prefix frontend"
pages_build_output_dir = "frontend/build"